KelCVBajaDivaManufaktur/Models/Transaksi.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KelCVBajaDivaManufaktur.Models
{
    public class Transaksi
    {

        [Key]
        public int Id { get; set; }

        public string? NamaPelanggan { get; set; }

        [ForeignKey("Produk")]
        public int ProdukId { get; set; }
        public Produk? Produk { get; set; }

        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd HH:mm:ss}", ApplyFormatInEditMode = true)]
        public DateTime TanggalBeli { get; set; }
        public int Jumlah { get; set; }
        public decimal TotalBayar { get; set; }
        public string? CaraBayar { get; set; }
    }
}

KelCVBajaDivaManufaktur/Controllers/TransaksisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KelCVBajaDivaManufaktur.Data;
using KelCVBajaDivaManufaktur.Models;

namespace KelCVBajaDivaManufaktur.Controllers
{
    public class TransaksisController : Controller
    {
        private readonly KelCVBajaDivaManufakturContext _context;

        public TransaksisController(KelCVBajaDivaManufakturContext context)
        {
            _context = context;
        }

        // GET: Transaksis
        public async Task<IActionResult> Index(string searchString)
        {
            if (_context.Transaksi == null)
            {
                return Problem("Entity set 'KelCVBajaDivaManufakturContext.Transaksi'  is null.");
            }

            var transaksis = from m in _context.Transaksi.Include(d => d.Produk)
                             select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                transaksis = transaksis.Where(s => s.NamaPelanggan!.Contains(searchString));
            }

            return View(await transaksis.ToListAsync());
        }

        // GET: Transaksis/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Transaksi == null)
            {
                return NotFound();
            }

            var transaksi = await _context.Transaksi.Include(d => d.Produk)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (transaksi == null)
            {
                return NotFound();
            }

            return View(transaksi);
        }

        // GET: Transaksis/Create
        public IActionResult Create()
        {
            ViewBag.HargaData = _context.Produk.ToDictionary(p => p.Id.ToString(), p => p.Harga);
            ViewData["ProdukId"] = new SelectList(_context.Produk, "Id", "NamaProduk");
            return View();
        }

        // POST: Transaksis/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NamaPelanggan,ProdukId,TanggalBeli,Jumlah,TotalBayar,CaraBayar")] Transaksi transaksi)
        {
            if (ModelState.IsValid)
            {
                _context.Add(transaksi);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProdukId"] = new SelectList(_context.Produk, "Id", "NamaProduk", transaksi.ProdukId);
            return View(transaksi);
        }

        // GET: Transaksis/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Transaksi == null)
            {
                return NotFound();
            }

            var transaksi = await _context.Transaksi.FindAsync(id);
            if (transaksi == null)
            {
                return NotFound();
            }
            ViewBag.HargaData = _context.Produk.ToDictionary(p => p.Id.ToString(), p => p.Harga);
            ViewData["ProdukId"] = new SelectList(_context.Produk, "Id", "NamaProduk");
            return View(transaksi);
        }

        // POST: Transaksis/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NamaPelanggan,ProdukId,TanggalBeli,Jumlah,TotalBayar,CaraBayar")] Transaksi transaksi)
        {
            ViewBag.HargaData = _context.Produk.ToDictionary(p => p.Id.ToString(), p => p.Harga);

            if (id != transaksi.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(transaksi);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TransaksiExists(transaksi.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProdukId"] = new SelectList(_context.Produk, "Id", "NamaProduk", transaksi.ProdukId);
            return View(transaksi);
        }

        // GET: Transaksis/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Transaksi == null)
            {
                return NotFound();
            }

            var transaksi = await _context.Transaksi
                .FirstOrDefaultAsync(m => m.Id == id);
            if (transaksi == null)
            {
                return NotFound();
            }

            return View(transaksi);
        }

        // POST: Transaksis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Transaksi == null)
            {
                return Problem("Entity set 'KelCVBajaDivaManufakturContext.Transaksi'  is null.");
            }
            var transaksi = await _context.Transaksi.FindAsync(id);
            if (transaksi != null)
            {
                _context.Transaksi.Remove(transaksi);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TransaksiExists(int id)
        {
          return (_context.Transaksi?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

KelCVBajaDivaManufaktur/Views/Transaksis/Create.cshtml
@model KelCVBajaDivaManufaktur.Models.Transaksi

@{
    Layout = "_layout";
    ViewData["Title"] = "Create";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CV Baja Diva Manufaktur - @ViewData["Title"]</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="~/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="~/js/select.dataTables.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/images/logo.jpg" />
</head>

<body>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Halaman Tambah Transaksi</h4>
            <p class="card-description">
                Tambah Transaksi
            </p>
            <form asp-action="Create" class="forms-sample">
                <div class="form-group">
                    <label asp-for="NamaPelanggan">Nama Pelanggan</label>
                    <input asp-for="NamaPelanggan" type="text" class="form-control" id="NamaPelanggan" placeholder="Masukkan Nama Pelanggan" required>
                    <span asp-validation-for="NamaPelanggan" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProdukId" class="control-label">Produk</label>
                    <select asp-for="ProdukId" class="form-control" asp-items="ViewBag.ProdukId">
                        <option value="">Select Produk</option>
                    </select>
                </div>

                <div class="form-group">
                    <label asp-for="TanggalBeli">Tanggal Beli</label>
                    @{
                        DateTime currentDateTime = ViewBag.CurrentDateTime != null ? (DateTime)ViewBag.CurrentDateTime : DateTime.Now;
                        string formattedDateTime = currentDateTime.ToString("yyyy-MM-ddTHH:mm");
                    }
                    <input asp-for="TanggalBeli" type="datetime-local" class="form-control" id="TanggalBeli" required
                           value="@formattedDateTime">
                    <span asp-validation-for="TanggalBeli" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Jumlah">Jumlah</label>
                    <input asp-for="Jumlah" type="number" class="form-control" id="Jumlah" placeholder="Masukkan Jumlah" required>
                    <span asp-validation-for="Jumlah" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="TotalBayar">Total Bayar</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text bg-primary text-white">Rp.</span>
                        </div>
                        <input asp-for="TotalBayar" type="number" class="form-control" id="TotalBayar"
                               placeholder="Masukkan Total Bayar" required readonly>
                        <div class="input-group-append">
                            <span class="input-group-text">.00</span>
                        </div>
                    </div>
                    <span asp-validation-for="TotalBayar" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="CaraBayar">Cara Bayar</label>
                    <select asp-for="CaraBayar" class="form-control" id="CaraBayar">
                        <option value="Cash">Cash</option>
                        <option value="Transfer">Transfer</option>
                    </select>
                    <span asp-validation-for="CaraBayar" class="text-danger"></span>
                </div>

                <button type="submit" class="btn btn-primary mr-2">Simpan</button>
                <a asp-action="Index" class="btn btn-light">Cancel</a>
            </form>

            <script>
                document.addEventListener('DOMContentLoaded', function () {
                    const jumlahInput = document.getElementById('Jumlah');
                    const produkSelect = document.getElementById('ProdukId');
                    const totalBayarInput = document.getElementById('TotalBayar');
                    const tanggalBeliInput = document.getElementById('TanggalBeli');
                    const hargaData = JSON.parse('@Html.Raw(Json.Serialize(ViewBag.HargaData))');

                    // Event listeners for changes in Jumlah and Produk
                    jumlahInput.addEventListener('input', calculateTotal);
                    produkSelect.addEventListener('change', calculateTotal);

                    // Set the current date, time, and minute for TanggalBeli input
                    const currentDate = new Date();
                    const formattedDate = currentDate.toISOString().split('T')[0];
                    const formattedTime = currentDate.toTimeString().split(' ')[0];
                    tanggalBeliInput.value = `${formattedDate} ${formattedTime}`;

                    function calculateTotal() {
                        const jumlah = parseInt(jumlahInput.value) || 0;
                        const selectedProdukId = produkSelect.value;
                        const harga = hargaData[selectedProdukId] || 0;

                        const totalBayar = jumlah * harga;
                        totalBayarInput.value = totalBayar.toFixed(2); // Format the total to two decimal places
                    }

                    // Initialize total calculation
                    calculateTotal();
                });
            </script>



        </div>
    </div>

    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }

</body>

</html>

KelCVBajaDivaManufaktur/Views/Transaksis/Delete.cshtml
@model KelCVBajaDivaManufaktur.Models.Transaksi

@{
    ViewData["Title"] = "Delete";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CV Baja Diva Manufaktur - @ViewData["Title"]</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="~/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="~/js/select.dataTables.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/images/logo.jpg" />
</head>

<body>

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Transaksi</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NamaPelanggan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NamaPelanggan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProdukId)
        </dt>
        <dd class = "col-sm-10">
                @Html.DisplayFor(model => model.ProdukId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TanggalBeli)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TanggalBeli)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Jumlah)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Jumlah)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalBayar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalBayar)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CaraBayar)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CaraBayar)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>


</body>
</html>

KelCVBajaDivaManufaktur/Views/Transaksis/Details.cshtml
@model KelCVBajaDivaManufaktur.Models.Transaksi

@{
    ViewData["Title"] = "Details";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CV Baja Diva Manufaktur - @ViewData["Title"]</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="~/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="~/js/select.dataTables.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/images/logo.jpg" />
</head>

<body>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Details Transaksi</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-3">Nama Pelanggan</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.NamaPelanggan)</dd>

                <dt class="col-sm-3">Produk</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Produk.NamaProduk)</dd>

                <dt class="col-sm-3">Tanggal Beli</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.TanggalBeli)</dd>

                <dt class="col-sm-3">Jumlah</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Jumlah)</dd>

                <dt class="col-sm-3">Total Bayar</dt>
                <dd class="col-sm-9">Rp. @Html.DisplayFor(model => model.TotalBayar)</dd>

                <dt class="col-sm-3">Cara Bayar</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.CaraBayar)</dd>
            </dl>

            <div class="mt-3">
                <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary">Edit</a>
                <a asp-action="Index" class="btn btn-light">Kembali</a>
            </div>
        </div>
    </div>


</body>
</html>

KelCVBajaDivaManufaktur/Views/Transaksis/Edit.cshtml
@model KelCVBajaDivaManufaktur.Models.Transaksi

@{
    ViewData["Title"] = "Edit";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CV Baja Diva Manufaktur - @ViewData["Title"]</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="~/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="~/js/select.dataTables.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/images/logo.jpg" />
</head>

<body>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Halaman Edit Transaksi</h4>
            <p class="card-description">
                Edit Transaksi
            </p>
            <form asp-action="Edit" class="forms-sample">
                <div class="form-group">
                    <label asp-for="NamaPelanggan">Nama Pelanggan</label>
                    <input asp-for="NamaPelanggan" type="text" class="form-control" id="NamaPelanggan" placeholder="Masukkan Nama Pelanggan" required>
                    <span asp-validation-for="NamaPelanggan" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ProdukId" class="control-label">Produk</label>
                    <select asp-for="ProdukId" class="form-control" asp-items="ViewBag.ProdukId">
                        <option value="">Select Produk</option>
                    </select>
                </div>

                <div class="form-group">
                    <label asp-for="TanggalBeli">Tanggal Beli</label>
                    @{
                        DateTime currentDateTime = ViewBag.CurrentDateTime != null ? (DateTime)ViewBag.CurrentDateTime : DateTime.Now;
                        string formattedDateTime = currentDateTime.ToString("yyyy-MM-ddTHH:mm");
                    }
                    <input asp-for="TanggalBeli" type="datetime-local" class="form-control" id="TanggalBeli" required
                           value="@formattedDateTime">
                    <span asp-validation-for="TanggalBeli" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Jumlah">Jumlah</label>
                    <input asp-for="Jumlah" type="number" class="form-control" id="Jumlah" placeholder="Masukkan Jumlah" required>
                    <span asp-validation-for="Jumlah" class="text-danger"></span>
                </div>


                <div class="form-group">
                    <label asp-for="TotalBayar">Total Bayar</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text bg-primary text-white">Rp.</span>
                        </div>
                        <input asp-for="TotalBayar" type="number" class="form-control" id="TotalBayar"
                               placeholder="Masukkan Total Bayar" required readonly>
                        <div class="input-group-append">
                            <span class="input-group-text">.00</span>
                        </div>
                    </div>
                    <span asp-validation-for="TotalBayar" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="CaraBayar">Cara Bayar</label>
                    <select asp-for="CaraBayar" class="form-control" id="CaraBayar">
                        <option value="Cash">Cash</option>
                        <option value="Transfer">Transfer</option>
                    </select>
                    <span asp-validation-for="CaraBayar" class="text-danger"></span>
                </div>

                <button type="submit" class="btn btn-primary mr-2">Simpan</button>
                <a asp-action="Index" class="btn btn-light">Cancel</a>
            </form>
            <script>
                document.addEventListener('DOMContentLoaded', function () {
                    const jumlahInput = document.getElementById('Jumlah');
                    const produkSelect = document.getElementById('ProdukId');
                    const totalBayarInput = document.getElementById('TotalBayar');
                    const tanggalBeliInput = document.getElementById('TanggalBeli');
                    const hargaData = JSON.parse('@Html.Raw(Json.Serialize(ViewBag.HargaData))');

                    // Event listeners for changes in Jumlah and Produk
                    jumlahInput.addEventListener('input', calculateTotal);
                    produkSelect.addEventListener('change', calculateTotal);

                    // Set the current date, time, and minute for TanggalBeli input
                    const currentDate = new Date();
                    const formattedDate = currentDate.toISOString().split('T')[0];
                    const formattedTime = currentDate.toTimeString().split(' ')[0];
                    tanggalBeliInput.value = `${formattedDate} ${formattedTime}`;

                    function calculateTotal() {
                        const jumlah = parseInt(jumlahInput.value) || 0;
                        const selectedProdukId = produkSelect.value;
                        const harga = hargaData[selectedProdukId] || 0;

                        const totalBayar = jumlah * harga;
                        totalBayarInput.value = totalBayar.toFixed(2); // Format the total to two decimal places
                    }

                    // Initialize total calculation
                    calculateTotal();
                });
            </script>
        </div>
    </div>

    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }

</body>
</html>

KelCVBajaDivaManufaktur/Views/Transaksis/Index.cshtml
@model IEnumerable<KelCVBajaDivaManufaktur.Models.Transaksi>

@{
    ViewData["Title"] = "Index";
}

<style>
    .table-container {
        max-height: 400px; /* Sesuaikan dengan tinggi maksimum yang diinginkan */
        overflow-y: auto;
    }
</style>

<div class="card">
    <div class="card-body">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="card-title">Data Transaksi</h4>
            <a asp-action="Create" class="btn btn-success">
                <i class="fa fa-plus"></i> Tambah
            </a>
        </div>
        <p class="card-description">Daftar Transaksi</p>

        <form asp-controller="Transaksis" asp-action="Index" method="get">
            <div class="input-group">
                <div class="input-group-prepend hover-cursor" id="search">
                    <span class="input-group-text" id="search">
                        <i class="icon-search"></i>
                    </span>
                </div>
                <input type="text" name="SearchString" class="form-control hover-cursor" id="search" placeholder="Search now" aria-label="search" aria-describedby="search">
            </div>
        </form>

        <div class="table-responsive mt-3 table-container">
            <table class="table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Pembeli</th>
                        <th>Produk</th>
                        <th>Tanggal Beli</th>
                        <th>Jumlah</th>
                        <th>Total Bayar</th>
                        <th>Cara Bayar</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        int rowNumber = 1; // Inisialisasi nomor baris
                    }
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@rowNumber</td>
                            <td>@Html.DisplayFor(modelItem => item.NamaPelanggan)</td>
                            <td>@Html.DisplayFor(modelItem => item.Produk.NamaProduk)</td>
                            <td>@Html.DisplayFor(modelItem => item.TanggalBeli)</td>
                            <td>@Html.DisplayFor(modelItem => item.Jumlah) Unit</td>
                            <td>Rp. @Html.DisplayFor(modelItem => item.TotalBayar)</td>
                            <td>@Html.DisplayFor(modelItem => item.CaraBayar)</td>
                            <td>
                                <form asp-action="Edit" asp-route-id="@item.Id" method="get">
                                    <button type="submit" class="btn btn-warning btn-sm btn-block" title="Edit">Edit</button>
                                </form>
                                <form asp-action="Details" asp-route-id="@item.Id" method="get">
                                    <button type="submit" class="btn btn-info btn-sm btn-block" title="Details">Details</button>
                                </form>
                                <form asp-action="Delete" asp-route-id="@item.Id" method="post" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                    <button type="submit" class="btn btn-danger btn-sm btn-block" title="Delete">Delete</button>
                                </form>
                            </td>
                        </tr>
                        rowNumber++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>