KelCVBajaDivaManufaktur/Models/Pengguna.cs
namespace KelCVBajaDivaManufaktur.Models
{
    public class Pengguna
    {
        public int Id { get; set; }
        public string? NamaPengguna { get; set; }
        public string? Username { get; set; }
        public string? Password { get; set; }
        public string? HakAkses { get; set; }
    }
}

KelCVBajaDivaManufaktur/Controllers/PenggunasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KelCVBajaDivaManufaktur.Data;
using KelCVBajaDivaManufaktur.Models;

namespace KelCVBajaDivaManufaktur.Controllers
{
    public class PenggunasController : Controller
    {
        private readonly KelCVBajaDivaManufakturContext _context;

        public PenggunasController(KelCVBajaDivaManufakturContext context)
        {
            _context = context;
        }

        // GET: Penggunas
        public async Task<IActionResult> Index(string searchString)
        {
            if (_context.Pengguna == null)
            {
                return Problem("\"Entity set 'KelCVBajaDivaManufakturContext.Pengguna'  is null.");
            }

            var penggunas = from m in _context.Pengguna
                             select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                penggunas = penggunas.Where(s => s.NamaPengguna!.Contains(searchString));
            }

            return View(await penggunas.ToListAsync());
        }

        // GET: Penggunas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pengguna == null)
            {
                return NotFound();
            }

            var pengguna = await _context.Pengguna
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pengguna == null)
            {
                return NotFound();
            }

            return View(pengguna);
        }

        // GET: Penggunas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Penggunas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NamaPengguna,Username,Password,HakAkses")] Pengguna pengguna)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pengguna);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pengguna);
        }

        // GET: Penggunas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pengguna == null)
            {
                return NotFound();
            }

            var pengguna = await _context.Pengguna.FindAsync(id);
            if (pengguna == null)
            {
                return NotFound();
            }
            return View(pengguna);
        }

        // POST: Penggunas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NamaPengguna,Username,Password,HakAkses")] Pengguna pengguna)
        {
            if (id != pengguna.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pengguna);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PenggunaExists(pengguna.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pengguna);
        }

        // GET: Penggunas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pengguna == null)
            {
                return NotFound();
            }

            var pengguna = await _context.Pengguna
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pengguna == null)
            {
                return NotFound();
            }

            return View(pengguna);
        }

        // POST: Penggunas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pengguna == null)
            {
                return Problem("Entity set 'KelCVBajaDivaManufakturContext.Pengguna'  is null.");
            }
            var pengguna = await _context.Pengguna.FindAsync(id);
            if (pengguna != null)
            {
                _context.Pengguna.Remove(pengguna);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PenggunaExists(int id)
        {
          return (_context.Pengguna?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

KelCVBajaDivaManufaktur/Views/Penggunas/Create.cshtml
@model KelCVBajaDivaManufaktur.Models.Pengguna

@{
    ViewData["Title"] = "Create";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CV Baja Diva Manufaktur - @ViewData["Title"]</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="~/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="~/js/select.dataTables.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/images/logo.jpg" />
</head>

<body>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Halaman Tambah Pengguna</h4>
            <p class="card-description">
                Tambah Pengguna
            </p>
            <form asp-action="Create" class="forms-sample">
                <div class="form-group">
                    <label asp-for="NamaPengguna">Nama Pengguna</label>
                    <input asp-for="NamaPengguna" type="text" class="form-control" id="NamaPengguna" placeholder="Masukkan Nama Pengguna" required>
                    <span asp-validation-for="NamaPengguna" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Username">Username</label>
                    <input asp-for="Username" type="text" class="form-control" id="Username" placeholder="Masukkan Username" required>
                    <span asp-validation-for="Username" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Password">Password</label>
                    <input asp-for="Password" type="password" class="form-control" id="Password" placeholder="Masukkan Password" required>
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="HakAkses">Hak Akses</label>
                    <select asp-for="HakAkses" class="form-control" id="HakAkses">
                        <option value="Admin">Admin</option>
                        <option value="Karyawan">Karyawan</option>
                        <option value="Supplier">Supplier</option>
                    </select>
                    <span asp-validation-for="HakAkses" class="text-danger"></span>
                </div>

                <button type="submit" class="btn btn-primary mr-2">Simpan</button>
                <button asp-action="Index" class="btn btn-light">Cancel</button>
            </form>
        </div>
    </div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

</body>
</html>

KelCVBajaDivaManufaktur/Views/Penggunas/Delete.cshtml
@model KelCVBajaDivaManufaktur.Models.Pengguna

@{
    ViewData["Title"] = "Delete";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CV Baja Diva Manufaktur - @ViewData["Title"]</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="~/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="~/js/select.dataTables.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/images/logo.jpg" />
</head>

<body>


<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pengguna</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NamaPengguna)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NamaPengguna)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Username)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Username)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Password)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Password)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HakAkses)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HakAkses)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

</body>
</html>

KelCVBajaDivaManufaktur/Views/Penggunas/Details.cshtml
@model KelCVBajaDivaManufaktur.Models.Pengguna

@{
    ViewData["Title"] = "Details";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CV Baja Diva Manufaktur - @ViewData["Title"]</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="~/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="~/js/select.dataTables.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/images/logo.jpg" />
</head>

<body>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Details Pengguna</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-3">Nama Pengguna</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.NamaPengguna)</dd>

                <dt class="col-sm-3">Username</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Username)</dd>

                <dt class="col-sm-3">Password</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Password)</dd>

                <dt class="col-sm-3">Hak Akses</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.HakAkses)</dd>
            </dl>

            <div class="mt-3">
                <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary">Edit</a>
                <a asp-action="Index" class="btn btn-light">Kembali</a>
            </div>
        </div>
    </div>


</body>
</html>

KelCVBajaDivaManufaktur/Views/Penggunas/Edit.cshtml
@model KelCVBajaDivaManufaktur.Models.Pengguna

@{
    ViewData["Title"] = "Edit";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CV Baja Diva Manufaktur - @ViewData["Title"]</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="~/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="~/js/select.dataTables.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/images/logo.jpg" />
</head>

<body>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Halaman Edit Pengguna</h4>
            <p class="card-description">
                Edit Pengguna
            </p>
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />

                <div class="form-group">
                    <label asp-for="NamaPengguna" class="control-label">Nama Pengguna</label>
                    <input asp-for="NamaPengguna" class="form-control" />
                    <span asp-validation-for="NamaPengguna" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Username" class="control-label">Username</label>
                    <input asp-for="Username" class="form-control" />
                    <span asp-validation-for="Username" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Password" class="control-label">Password</label>
                    <input asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="HakAkses">Hak Akses</label>
                    <select asp-for="HakAkses" class="form-control" id="HakAkses">
                        <option value="Admin">Admin</option>
                        <option value="Karyawan">Karyawan</option>
                        <option value="Supplier">Supplier</option>
                    </select>
                    <span asp-validation-for="HakAkses" class="text-danger"></span>
                </div>

                <div class="mt-3">
                    <button type="submit" class="btn btn-primary">Simpan</button>
                    <a asp-action="Index" class="btn btn-light">Cancel</a>
                </div>
            </form>
        </div>
    </div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

KelCVBajaDivaManufaktur/Views/Penggunas/Index.cshtml
@model IEnumerable<KelCVBajaDivaManufaktur.Models.Pengguna>

@{
    ViewData["Title"] = "Index";
}
<style>
    .table-container {
        max-height: 400px; /* Sesuaikan dengan tinggi maksimum yang diinginkan */
        overflow-y: auto;
    }
</style>
<div class="card">
    <div class="card-body">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="card-title">Data Pengguna</h4>
            <a asp-action="Create" class="btn btn-success">
                <i class="fa fa-plus"></i> Tambah
            </a>
        </div>
        <p class="card-description">Daftar Pengguna</p>

        <form asp-controller="Penggunas" asp-action="Index" method="get">
            <div class="input-group">
                <div class="input-group-prepend hover-cursor" id="search">
                    <span class="input-group-text" id="search">
                        <i class="icon-search"></i>
                    </span>
                </div>
                <input type="text" name="SearchString" class="form-control hover-cursor" id="search" placeholder="Search now" aria-label="search" aria-describedby="search">
            </div>
        </form>

        <div class="table-responsive mt-3 table-container">
            <table class="table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>@Html.DisplayNameFor(model => model.NamaPengguna)</th>
                        <th>@Html.DisplayNameFor(model => model.Username)</th>
                        <th>@Html.DisplayNameFor(model => model.Password)</th>
                        <th>@Html.DisplayNameFor(model => model.HakAkses)</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        int rowNumber = 1; // Inisialisasi nomor baris
                    }
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@rowNumber</td>
                            <td>@Html.DisplayFor(modelItem => item.NamaPengguna)</td>
                            <td>@Html.DisplayFor(modelItem => item.Username)</td>
                            <td>@Html.DisplayFor(modelItem => item.Password)</td>
                            <td>@Html.DisplayFor(modelItem => item.HakAkses)</td>
                            <td class="d-flex">
                                <form asp-action="Edit" asp-route-id="@item.Id" method="get">
                                    <button type="submit" class="btn btn-warning btn-sm mr-1" title="Edit">
                                        Edit
                                    </button>
                                </form>
                                <form asp-action="Details" asp-route-id="@item.Id" method="get">
                                    <button type="submit" class="btn btn-info btn-sm mr-1" title="Details">
                                        Details
                                    </button>
                                </form>
                                <form asp-action="Delete" asp-route-id="@item.Id" method="post">
                                    <button type="submit" class="btn btn-danger btn-sm" title="Delete">
                                        Delete
                                    </button>
                                </form>
                            </td>
                        </tr>
                        rowNumber++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>