KelCVBajaDivaManufaktur/Models/Supplier.cs
using System.ComponentModel.DataAnnotations;

namespace KelCVBajaDivaManufaktur.Models
{
    public class Supplier
    {
        [Key]
        public int Id { get; set; }
        public string? NamaSupplier { get; set; }
        public string? Alamat { get; set; }
        public string? NoHP { get; set; }
    }
}

KelCVBajaDivaManufaktur/Controllers/SuppliersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KelCVBajaDivaManufaktur.Data;
using KelCVBajaDivaManufaktur.Models;

namespace KelCVBajaDivaManufaktur.Controllers
{
    public class SuppliersController : Controller
    {
        private readonly KelCVBajaDivaManufakturContext _context;

        public SuppliersController(KelCVBajaDivaManufakturContext context)
        {
            _context = context;
        }

        // GET: Suppliers
        public async Task<IActionResult> Index(string searchString)
        {
            if (_context.Supplier == null)
            {
                return Problem("Entity set 'KelCVBajaDivaManufakturContext.Supplier'  is null.");
            }

            var suppliers = from m in _context.Supplier
                          select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                suppliers = suppliers.Where(s => s.NamaSupplier!.Contains(searchString));
            }

            return View(await suppliers.ToListAsync());
        }

        // GET: Suppliers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Supplier == null)
            {
                return NotFound();
            }

            var supplier = await _context.Supplier
                .FirstOrDefaultAsync(m => m.Id == id);
            if (supplier == null)
            {
                return NotFound();
            }

            return View(supplier);
        }

        // GET: Suppliers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Suppliers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NamaSupplier,Alamat,NoHP")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                _context.Add(supplier);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(supplier);
        }

        // GET: Suppliers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Supplier == null)
            {
                return NotFound();
            }

            var supplier = await _context.Supplier.FindAsync(id);
            if (supplier == null)
            {
                return NotFound();
            }
            return View(supplier);
        }

        // POST: Suppliers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NamaSupplier,Alamat,NoHP")] Supplier supplier)
        {
            if (id != supplier.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(supplier);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SupplierExists(supplier.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(supplier);
        }

        // GET: Suppliers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Supplier == null)
            {
                return NotFound();
            }

            var supplier = await _context.Supplier
                .FirstOrDefaultAsync(m => m.Id == id);
            if (supplier == null)
            {
                return NotFound();
            }

            return View(supplier);
        }

        // POST: Suppliers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Supplier == null)
            {
                return Problem("Entity set 'KelCVBajaDivaManufakturContext.Supplier'  is null.");
            }
            var supplier = await _context.Supplier.FindAsync(id);
            if (supplier != null)
            {
                _context.Supplier.Remove(supplier);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SupplierExists(int id)
        {
          return (_context.Supplier?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

KelCVBajaDivaManufaktur/Views/Suppliers/Create.cshtml
@model KelCVBajaDivaManufaktur.Models.Supplier

@{
    ViewData["Title"] = "Create";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CV Baja Diva Manufaktur - @ViewData["Title"]</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="~/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="~/js/select.dataTables.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/images/logo.jpg" />
</head>

<body>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Halaman Tambah Supplier</h4>
            <p class="card-description">
                Tambah Supplier
            </p>
            <form asp-action="Create" class="forms-sample">
                <div class="form-group">
                    <label asp-for="NamaSupplier">Nama Supplier</label>
                    <input asp-for="NamaSupplier" type="text" class="form-control" id="NamaSupplier" placeholder="Masukkan Nama Supplier" required>
                    <span asp-validation-for="NamaSupplier" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Alamat">Alamat</label>
                    <textarea asp-for="Alamat" class="form-control" id="Alamat" rows="4" placeholder="Masukkan Alamat"></textarea>
                    <span asp-validation-for="Alamat" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="NoHP">Nomor HP</label>
                    <input asp-for="NoHP" type="number" class="form-control" id="NoHP" placeholder="Masukkan Nomor HP" required>
                    <span asp-validation-for="NoHP" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary mr-2">Simpan</button>
                <button asp-action="Index" class="btn btn-light">Cancel</button>
            </form>
        </div>
    </div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

</body>
</html>

KelCVBajaDivaManufaktur/Views/Suppliers/Delete.cshtml
@model KelCVBajaDivaManufaktur.Models.Supplier

@{
    ViewData["Title"] = "Delete";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CV Baja Diva Manufaktur - @ViewData["Title"]</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="~/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="~/js/select.dataTables.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/images/logo.jpg" />
</head>

<body>

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Supplier</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NamaSupplier)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NamaSupplier)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Alamat)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Alamat)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoHP)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoHP)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

</body>
</html>

KelCVBajaDivaManufaktur/Views/Suppliers/Details.cshtml
@model KelCVBajaDivaManufaktur.Models.Supplier

@{
    ViewData["Title"] = "Details";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CV Baja Diva Manufaktur - @ViewData["Title"]</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="~/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="~/js/select.dataTables.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/images/logo.jpg" />
</head>

<body>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Details Supplier</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-3">Nama Supplier</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.NamaSupplier)</dd>

                <dt class="col-sm-3">Alamat</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Alamat)</dd>

                <dt class="col-sm-3">Nomor HP</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.NoHP)</dd>
            </dl>

        <div class="mt-3">
            <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary">Edit</a>
            <a asp-action="Index" class="btn btn-light">Kembali</a>
        </div>
        </div>

    </div>


</body>
</html>

KelCVBajaDivaManufaktur/Views/Suppliers/Edit.cshtml
@model KelCVBajaDivaManufaktur.Models.Supplier

@{
    ViewData["Title"] = "Edit";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CV Baja Diva Manufaktur - @ViewData["Title"]</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="~/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="~/js/select.dataTables.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/images/logo.jpg" />
</head>

<body>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Halaman Edit Supplier</h4>
            <p class="card-description">
                Edit Supplier
            </p>
            <form asp-action="Edit">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />

                <div class="form-group">
                    <label asp-for="NamaSupplier" class="control-label">Nama Supplier</label>
                    <input asp-for="NamaSupplier" class="form-control" />
                    <span asp-validation-for="NamaSupplier" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="Alamat" class="control-label">Alamat</label>
                    <textarea asp-for="Alamat" class="form-control" rows="4"></textarea>
                    <span asp-validation-for="Alamat" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label asp-for="NoHP" class="control-label">Nomor HP</label>
                    <input asp-for="NoHP" type="number" class="form-control" />
                    <span asp-validation-for="NoHP" class="text-danger"></span>
                </div>

                <button type="submit" class="btn btn-primary mr-2">Simpan</button>
                <button asp-action="Index" class="btn btn-light">Cancel</button>
            </form>
        </div>
    </div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

</body>
</html>

KelCVBajaDivaManufaktur/Views/Suppliers/Index.cshtml
@model IEnumerable<KelCVBajaDivaManufaktur.Models.Supplier>

@{
    ViewData["Title"] = "Index";
}

<style>
    .table-container {
        max-height: 400px; /* Sesuaikan dengan tinggi maksimum yang diinginkan */
        overflow-y: auto;
    }
</style>


<div class="card">
    <div class="card-body">
        <div class="d-flex justify-content-between align-items-center">
            <h4 class="card-title">Data Supplier</h4>
            <a asp-action="Create" class="btn btn-success">
                <i class="fa fa-plus"></i> Tambah
            </a>
        </div>
        <p class="card-description">Daftar Supplier</p>

        <form asp-controller="Suppliers" asp-action="Index" method="get">
            <div class="input-group">
                <div class="input-group-prepend hover-cursor" id="search">
                    <span class="input-group-text" id="search">
                        <i class="icon-search"></i>
                    </span>
                </div>
                <input type="text" name="SearchString" class="form-control hover-cursor" id="search" placeholder="Search now" aria-label="search" aria-describedby="search">
            </div>
        </form>

        <div class="table-responsive mt-3 table-container">
            <table class="table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Nama Supplier</th>
                        <th>Alamat</th>
                        <th>No HP</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        int rowNumber = 1; // Inisialisasi nomor baris
                    }
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@rowNumber</td>
                            <td>@Html.DisplayFor(modelItem => item.NamaSupplier)</td>
                            <td>@Html.DisplayFor(modelItem => item.Alamat)</td>
                            <td>@Html.DisplayFor(modelItem => item.NoHP)</td>
                            <td class="d-flex">
                                <form asp-action="Edit" asp-route-id="@item.Id" method="get">
                                    <button type="submit" class="btn btn-warning btn-sm mr-1" title="Edit">
                                        Edit
                                    </button>
                                </form>
                                <form asp-action="Details" asp-route-id="@item.Id" method="get">
                                    <button type="submit" class="btn btn-info btn-sm mr-1" title="Details">
                                        Details
                                    </button>
                                </form>
                                <form asp-action="Delete" asp-route-id="@item.Id" method="post">
                                    <button type="submit" class="btn btn-danger btn-sm" title="Delete">
                                        Delete
                                    </button>
                                </form>
                            </td>
                        </tr>
                        rowNumber++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>