KelCVBajaDivaManufaktur/Models/BahanBaku.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KelCVBajaDivaManufaktur.Models
{
    public class BahanBaku
    {
        [Key]
        public int Id { get; set; }
        public string? NamaBahan { get; set; }
        public int Stok { get; set; }

        public string? Satuan { get; set; }

        [ForeignKey("Supplier")]
        public int SupplierId { get; set; }
        public Supplier? Supplier { get; set; }
    }
}

KelCVBajaDivaManufaktur/Controllers/BahanBakusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KelCVBajaDivaManufaktur.Data;
using KelCVBajaDivaManufaktur.Models;

namespace KelCVBajaDivaManufaktur.Controllers
{
    public class BahanBakusController : Controller
    {
        private readonly KelCVBajaDivaManufakturContext _context;

        public BahanBakusController(KelCVBajaDivaManufakturContext context)
        {
            _context = context;
        }

        // GET: BahanBakus
        public async Task<IActionResult> Index(string searchString)
        {
            if (_context.BahanBaku == null)
            {
                return Problem("Entity set 'KelCVBajaDivaManufakturContext.BahanBaku'  is null.");
            }

            var bahanbakus = from m in _context.BahanBaku.Include(d => d.Supplier)
                             select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                bahanbakus = bahanbakus.Where(s => s.NamaBahan!.Contains(searchString));
            }

            return View(await bahanbakus.ToListAsync());
        }

        [HttpPost]
        public async Task<IActionResult> TambahStok(int id)
        {
            var bahanBaku = await _context.BahanBaku.FindAsync(id);

            if (bahanBaku == null)
            {
                return NotFound();
            }

            // Contoh penambahan stok (di sini stok ditambah satu)
            bahanBaku.Stok += 1;

            _context.Update(bahanBaku);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }


        // GET: BahanBakus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.BahanBaku == null)
            {
                return NotFound();
            }

            var bahanBaku = await _context.BahanBaku.Include(d => d.Supplier)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bahanBaku == null)
            {
                return NotFound();
            }

            return View(bahanBaku);
        }

        // GET: BahanBakus/Create
        public IActionResult Create()
        {
            ViewData["SupplierId"] = new SelectList(_context.Supplier, "Id", "NamaSupplier");
            return View();
        }

        // POST: BahanBakus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NamaBahan,Stok,Satuan,SupplierId")] BahanBaku bahanBaku)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bahanBaku);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SupplierId"] = new SelectList(_context.Supplier, "Id", "NamaSupplier", bahanBaku.SupplierId);
            return View(bahanBaku);
        }

        // GET: BahanBakus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.BahanBaku == null)
            {
                return NotFound();
            }

            var bahanBaku = await _context.BahanBaku.FindAsync(id);
            if (bahanBaku == null)
            {
                return NotFound();
            }
            ViewData["SupplierId"] = new SelectList(_context.Supplier, "Id", "NamaSupplier");
            return View(bahanBaku);
        }

        // POST: BahanBakus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,NamaBahan,Stok,Satuan,SupplierId")] BahanBaku bahanBaku)
        {
            if (id != bahanBaku.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bahanBaku);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BahanBakuExists(bahanBaku.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["SupplierId"] = new SelectList(_context.Supplier, "Id", "NamaSupplier", bahanBaku.SupplierId);
            return View(bahanBaku);
        }

        // GET: BahanBakus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.BahanBaku == null)
            {
                return NotFound();
            }

            var bahanBaku = await _context.BahanBaku
                .FirstOrDefaultAsync(m => m.Id == id);
            if (bahanBaku == null)
            {
                return NotFound();
            }

            return View(bahanBaku);
        }

        // POST: BahanBakus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.BahanBaku == null)
            {
                return Problem("Entity set 'KelCVBajaDivaManufakturContext.BahanBaku'  is null.");
            }
            var bahanBaku = await _context.BahanBaku.FindAsync(id);
            if (bahanBaku != null)
            {
                _context.BahanBaku.Remove(bahanBaku);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BahanBakuExists(int id)
        {
          return (_context.BahanBaku?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

KelCVBajaDivaManufaktur/Controllers/PesanBBsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KelCVBajaDivaManufaktur.Data;
using KelCVBajaDivaManufaktur.Models;

namespace KelCVBajaDivaManufaktur.Controllers
{
    public class PesanBBsController : Controller
    {
        private readonly KelCVBajaDivaManufakturContext _context;

        public PesanBBsController(KelCVBajaDivaManufakturContext context)
        {
            _context = context;
        }

        // GET: PesanBBs
        public async Task<IActionResult> Index()
        {
            var kelCVBajaDivaManufakturContext = _context.PesanBB
                .Include(p => p.Supplier)
                .Include(p => p.BahanBaku);
            return View(await kelCVBajaDivaManufakturContext.ToListAsync());
        }

        // GET: PesanBBs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.PesanBB == null)
            {
                return NotFound();
            }

            var pesanBB = await _context.PesanBB
                .Include(p => p.Supplier)
                .Include(p => p.BahanBaku)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pesanBB == null)
            {
                return NotFound();
            }

            return View(pesanBB);
        }

        // GET: PesanBBs/Create
        public IActionResult Create()
        {
            ViewData["SupplierId"] = new SelectList(_context.Supplier, "Id", "NamaSupplier");
            ViewData["BahanBakuId"] = new SelectList(_context.BahanBaku, "Id", "NamaBahan");
            return View();
        }

        // POST: PesanBBs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // POST: PesanBBs/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,BahanBakuId,StokBB,SatuanBB,SupplierId")] PesanBB pesanBB)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pesanBB);
                await _context.SaveChangesAsync();
                TempData["SuccessMessage"] = "Pesanan berhasil dikirim.";
                return RedirectToAction("Index", "BahanBakus"); // Specify the controller and action to redirect to
            }
            ViewData["SupplierId"] = new SelectList(_context.Supplier, "Id", "NamaSupplier", pesanBB.SupplierId);
            ViewData["BahanBakuId"] = new SelectList(_context.BahanBaku, "Id", "NamaBahan", pesanBB.SupplierId);
            return View(pesanBB);
        }


        // GET: PesanBBs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PesanBB == null)
            {
                return NotFound();
            }

            var pesanBB = await _context.PesanBB.FindAsync(id);
            if (pesanBB == null)
            {
                return NotFound();
            }
            ViewData["SupplierId"] = new SelectList(_context.Supplier, "Id", "NamaSupplier", pesanBB.SupplierId);
            ViewData["BahanBakuId"] = new SelectList(_context.BahanBaku, "Id", "NamaBahan", pesanBB.SupplierId);
            return View(pesanBB);
        }

        // POST: PesanBBs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BahanBakuId,StokBB,SatuanBB,SupplierId")] PesanBB pesanBB)
        {
            if (id != pesanBB.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pesanBB);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PesanBBExists(pesanBB.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SupplierId"] = new SelectList(_context.Supplier, "Id", "NamaSupplier", pesanBB.SupplierId);
            ViewData["BahanBakuId"] = new SelectList(_context.BahanBaku, "Id", "NamaBahan", pesanBB.SupplierId);
            return View(pesanBB);
        }

        // GET: PesanBBs/Delete/5
        public async Task<IActionResult> Delete(int? id, string dataAction)
        {

            if (id == null || _context.PesanBB == null)
            {
                return NotFound();
            }

            var pesanBB = await _context.PesanBB
                .Include(p => p.Supplier)
                .Include(p => p.BahanBaku)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pesanBB == null)
            {
                return NotFound();
            }
           
            if (dataAction == "accept")
            {
                // Pesanan diterima
                TempData["SuccessMessage"] = "Pesanan diterima.";
            }
            else if (dataAction == "reject")
            {
                // Pesanan ditolak
                TempData["SuccessMessage"] = "Pesanan ditolak.";
            }

            return View(pesanBB);
        }

        // POST: PesanBBs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PesanBB == null)
            {
                return Problem("Entity set 'KelCVBajaDivaManufakturContext.PesanBB'  is null.");
            }
            var pesanBB = await _context.PesanBB.FindAsync(id);
            if (pesanBB != null)
            {
                _context.PesanBB.Remove(pesanBB);
            }

           

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PesanBBExists(int id)
        {
          return (_context.PesanBB?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

KelCVBajaDivaManufaktur/Views/BahanBakus/Create.cshtml
@model KelCVBajaDivaManufaktur.Models.BahanBaku

@{
    Layout = "_Layout";
    ViewData["Title"] = "Create";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CV Baja Diva Manufaktur - @ViewData["Title"]</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="~/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="~/js/select.dataTables.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/images/logo.jpg" />
</head>
<body>
<div class="card">
    <div class="card-body">
        <h4 class="card-title">Halaman Tambah Bahan Baku</h4>
        <p class="card-description">
            Tambah Bahan Baku
        </p>
        <form asp-action="Create" class="forms-sample">
            <div class="form-group">
                <label asp-for="NamaBahan" >Nama Bahan Baku</label>
                <input asp-for="NamaBahan" type="text" class="form-control" id="NamaBahan" placeholder="Masukkan Nama Bahan Baku" required>
                <span asp-validation-for="NamaBahan" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Stok">Jumlah Stok</label>
                <input asp-for="Stok" type="number" class="form-control" id="Stok" placeholder="Masukkan Jumlah Stok">
                <span asp-validation-for="Stok" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Satuan">Satuan</label>
                <select asp-for="Satuan" class="form-control" id="Satuan">
                        <option>pcs</option>
                        <option>keping</option>
                        <option>batang</option>
                        <option>gram</option>
                        <option>kg</option>
                        <option>m</option>
                        <option>mm</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="SupplierId" class="control-label">Supplier</label>
                <select asp-for="SupplierId" class="form-control" asp-items="ViewBag.SupplierId"></select>
            </div>

            <button type="submit" class="btn btn-primary mr-2">Simpan</button>
            <button asp-action="Index" class="btn btn-light">Cancel</button>
        </form>
    </div>
</div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @section Scripts {
        @{
            await Html.RenderPartialAsync("_ValidationScriptsPartial");
        }
    }
    <!-- plugins:js -->
    <script src="vendors/js/vendor.bundle.base.js"></script>
    <!-- endinject -->
    <!-- Plugin js for this page -->
    <script src="vendors/chart.js/Chart.min.js"></script>
    <script src="vendors/datatables.net/jquery.dataTables.js"></script>
    <script src="vendors/datatables.net-bs4/dataTables.bootstrap4.js"></script>
    <script src="js/dataTables.select.min.js"></script>

    <!-- End plugin js for this page -->
    <!-- inject:js -->
    <script src="js/off-canvas.js"></script>
    <script src="js/hoverable-collapse.js"></script>
    <script src="js/template.js"></script>
    <script src="js/settings.js"></script>
    <script src="js/todolist.js"></script>
    <!-- endinject -->
    <!-- Custom js for this page-->
    <script src="js/dashboard.js"></script>
    <script src="js/Chart.roundedBarCharts.js"></script>
    <!-- End custom js for this page-->
</body>
</html>

KelCVBajaDivaManufaktur/Views/BahanBakus/Delete.cshtml
@model KelCVBajaDivaManufaktur.Models.BahanBaku

@{
    ViewData["Title"] = "Delete";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CV Baja Diva Manufaktur - @ViewData["Title"]</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="~/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="~/js/select.dataTables.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/images/logo.jpg" />
</head>

<body>
<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BahanBaku</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NamaBahan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NamaBahan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stok)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stok)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Satuan)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Satuan)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Supplier)
        </dt>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

</body>
</html>

KelCVBajaDivaManufaktur/Views/BahanBakus/Details.cshtml
@model KelCVBajaDivaManufaktur.Models.BahanBaku

@{
    ViewData["Title"] = "Details";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>CV Baja Diva Manufaktur - @ViewData["Title"]</title>

    <!-- plugins:css -->
    <link rel="stylesheet" href="~/vendors/feather/feather.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" href="~/vendors/css/vendor.bundle.base.css">
    <!-- endinject -->
    <!-- Plugin css for this page -->
    <link rel="stylesheet" href="~/vendors/datatables.net-bs4/dataTables.bootstrap4.css">
    <link rel="stylesheet" href="~/vendors/ti-icons/css/themify-icons.css">
    <link rel="stylesheet" type="text/css" href="~/js/select.dataTables.min.css">
    <!-- End plugin css for this page -->
    <!-- inject:css -->
    <link rel="stylesheet" href="~/css/vertical-layout-light/style.css">
    <!-- endinject -->
    <link rel="shortcut icon" href="~/images/logo.jpg" />
</head>

<body>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Details Bahan Baku</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-3">Nama Bahan Baku</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.NamaBahan)</dd>

                <dt class="col-sm-3">Jumlah Stok</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Stok)</dd>

                <dt class="col-sm-3">Satuan</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Satuan)</dd>

                <dt class="col-sm-3">Supplier</dt>
                <dd class="col-sm-9">@Html.DisplayFor(model => model.Supplier.NamaSupplier)</dd>
            </dl>
            
        <div class="mt-3">
            <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary">Edit</a>
            <a asp-action="Index" class="btn btn-light">Kembali</a>
        </div>

        </div>

    </div>



</body>
</html>

KelCVBajaDivaManufaktur/Views/BahanBakus/Index.cshtml
@inject IHttpContextAccessor httpContextaccessor
@model IEnumerable<KelCVBajaDivaManufaktur.Models.BahanBaku>

@{
    ViewData["Title"] = "Index";
}
<style>
    .table-container {
        max-height: 400px; /* Sesuaikan dengan tinggi maksimum yang diinginkan */
        overflow-y: auto;
    }
</style>
      @if (httpContextaccessor.HttpContext.Request.Cookies["hak_akses"] == "Supplier")
{
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-between align-items-center">
                <h4 class="card-title">Data Bahan Baku</h4>
                <a asp-action="Create" class="btn btn-success">
                    <i class="fa fa-plus"></i> Tambah
                </a>
            </div>

            <p class="card-description">Daftar Bahan Baku Tersedia</p>
            <form asp-controller="BahanBakus" asp-action="Index" method="get">
                <div class="input-group">
                    <div class="input-group-prepend hover-cursor" id="search">
                        <span class="input-group-text" id="search">
                            <i class="icon-search"></i>
                        </span>
                    </div>
                    <input type="text" name="SearchString" class="form-control hover-cursor" id="search" placeholder="Search now" aria-label="search" aria-describedby="search">
                </div>
            </form>

            <div class="table-responsive mt-3 table-container">
                <table class="table">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Bahan</th>
                            <th>Stok</th>
                            <th>Satuan</th>
                            <th>Client</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int rowNumber = 1; // Inisialisasi nomor baris
                        }
                        @foreach (var item in Model.Where(m => m.Supplier.NamaSupplier == "PT. Texco"))
                        {
                            <tr>
                                <td>@rowNumber</td>
                                <td>@Html.DisplayFor(modelItem => item.NamaBahan)</td>
                                <td>@Html.DisplayFor(modelItem => item.Stok)</td>
                                <td>@Html.DisplayFor(modelItem => item.Satuan)</td>
                                <td>CV Baja Diva Manufaktur</td>
                                <td class="d-flex">
                                    <form id="formTambahStok" asp-action="TambahStok" asp-route-id="@item.Id" method="post">
                                        <button type="submit" class="btn btn-primary btn-sm mr-1">
                                            + Stok
                                        </button>
                                    </form>
                                    <form asp-action="Edit" asp-route-id="@item.Id" method="get">
                                        <button type="submit" class="btn btn-warning btn-sm mr-1" title="Edit">
                                            Edit
                                        </button>
                                    </form>
                                    <form asp-action="Details" asp-route-id="@item.Id" method="get">
                                        <button type="submit" class="btn btn-info btn-sm mr-1" title="Details">
                                            Details
                                        </button>
                                    </form>
                                    <form asp-action="Delete" asp-route-id="@item.Id" method="post">
                                        <button type="submit" class="btn btn-danger btn-sm" title="Delete">
                                            Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            rowNumber++;
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

}
else
{
    <div class="card">
        <div class="card-body">
            <div class="d-flex justify-content-between align-items-center">
                <h4 class="card-title">Data Bahan Baku</h4>
                <div class="d-flex">
                    <a asp-controller="PesanBBs" asp-action="Create" class="btn btn-success mr-3">
                        <i class="fa fa-plus"></i> Pesan
                    </a>
                    <a asp-action="Create" class="btn btn-primary mr-3">
                        <i class="fa fa-plus"></i> Tambah
                    </a>
                   
                </div>
            </div>
            <p class="card-description">Daftar Bahan Baku Tersedia</p>
            <form asp-controller="BahanBakus" asp-action="Index" method="get">
                <div class="input-group">
                    <div class="input-group-prepend hover-cursor" id="search">
                        <span class="input-group-text" id="search">
                            <i class="icon-search"></i>
                        </span>
                    </div>
                    <input type="text" name="SearchString" class="form-control hover-cursor" id="search" placeholder="Search now" aria-label="search" aria-describedby="search">
                </div>
            </form>

            <div class="table-responsive mt-3 table-container">
                <table class="table">
                    <thead>
                        <tr>
                            <th>No</th>
                            <th>Nama Bahan</th>
                            <th>Stok</th>
                            <th>Satuan</th>
                            <th>Supplier</th>
                            <th>Aksi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @{
                            int rowNumber = 1; // Inisialisasi nomor baris
                        }
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@rowNumber</td>
                                <td>@Html.DisplayFor(modelItem => item.NamaBahan)</td>
                                <td>@Html.DisplayFor(modelItem => item.Stok)</td>
                                <td>@Html.DisplayFor(modelItem => item.Satuan)</td>
                                <td>@Html.DisplayFor(modelItem => item.Supplier.NamaSupplier)</td>
                                <td class="d-flex">
                                    <form asp-action="Details" asp-route-id="@item.Id" method="get">
                                        <button type="submit" class="btn btn-info btn-sm mr-1" title="Details">
                                            Details
                                        </button>
                                    </form>
                                </td>
                            </tr>
                            rowNumber++;
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}
<script>
    $(document).ready(function () {
        $('#formTambahStok').submit(function (e) {
            e.preventDefault(); // Mencegah pengiriman formulir

            // Mendapatkan ID BahanBaku dari atribut form
            var bahanBakuId = $(this).attr('data-id');

            // Di sini Anda dapat menambahkan logika untuk penambahan stok
            // Misalnya, Anda bisa melakukan permintaan AJAX ke server
            // untuk menangani penambahan stok.

            // Contoh permintaan AJAX menggunakan jQuery
            $.ajax({
                url: '/BahanBakus/TambahStok/' + bahanBakuId,
                type: 'POST',
                success: function (data) {
                    alert('Stok berhasil ditambahkan.');
                },
                error: function () {
                    alert('Gagal menambahkan stok.');
                }
            });
        });
    });
</script>

@{
    var successMessage = TempData["SuccessMessage"] as string;
}

@if (!string.IsNullOrEmpty(successMessage))
{
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            alert('@successMessage');
        });
    </script>
}